name: buildx

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET: Dockerfile

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm,linux/arm64/v8 \
            --output "type=image,push=false" \
            --file ./Dockerfile .

      - name: Dockerize
        if: success()
        uses: manusa/actions-publish-docker@master
        with:
          name: shanedabes/znc
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tag script: |
            return context.ref
              .replace('refs/heads/
              .replace('refs/tags/'
              .replace('refs/pull/'
              .replace(/\//g, '_')
              .replace(/#/g, '');
          registry: hub.docker.com
